services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"  
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-agent
    restart: unless-stopped
    environment:
      - KUBECONFIG=/root/.kube/config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock        # for docker builds
      - ~/.kube:/root/.kube                              # for kubectl access
    depends_on:
      - jenkins-master
    networks:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins:
    driver: bridge
