services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: jenkins-master
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/var/jenkins_home:/var/jenkins_home
    networks:
      - jenkins

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: jenkins-agent
    restart: unless-stopped
    depends_on:
      - jenkins-master
    ports:
      - "2222:22"
    networks:
      - jenkins
    volumes:
      - ./ssh:/home/jenkins/.ssh:ro

networks:
  jenkins:
    driver: bridge
